import React, { useRef, useEffect } from 'react';

export default function ChatInput({ query, setQuery, handleChat, loading }) {
  const inputRef = useRef(null);

  // Auto-focus input on load
  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  return (
    <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-white via-white to-transparent pt-10 pb-6 px-4">
      <div className="max-w-3xl mx-auto">
        <form 
          onSubmit={handleChat} 
          className="relative flex items-end bg-white border border-gray-300 shadow-lg shadow-gray-200/50 rounded-xl overflow-hidden focus-within:ring-1 focus-within:ring-gray-900 focus-within:border-gray-900 transition-all"
        >
          <textarea
            ref={inputRef}
            placeholder="Ask your organizational graph..."
            className="w-full max-h-[200px] bg-transparent pl-4 pr-12 py-3.5 text-[15px] focus:outline-none text-gray-900 resize-none overflow-y-auto"
            rows="1"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              // Auto-resize textarea logic
              e.target.style.height = 'auto';
              e.target.style.height = `${Math.min(e.target.scrollHeight, 200)}px`;
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                if (query.trim() && !loading) handleChat(e);
              }
            }}
            disabled={loading}
          />
          <button
            type="submit"
            disabled={loading || !query.trim()}
            className="absolute right-2 bottom-2 p-1.5 bg-gray-900 text-white rounded-lg hover:bg-gray-800 disabled:bg-gray-100 disabled:text-gray-400 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M5 10l7-7m0 0l7 7m-7-7v18" />
            </svg>
          </button>
        </form>
        
        <div className="text-center mt-2">
          <span className="text-[10px] text-gray-400 font-medium">
            Responses are generated by LangGraph & Groq. Verify critical information.
          </span>
        </div>
      </div>
    </div>
  );
}